In [34]:
import pandas as pd
import os
import numpy as np

In [20]:
ordre_dataset = ['UCF', 'EPIC', 'HAC']
ordre_modalites = ["video", "flow"]

In [14]:
#results_file = "results_moda_wise_far_ood.csv"
results_file = "results_moda_wise_ucf_react_video.csv"
df_results = pd.read_csv(results_file).drop(["backbone", "method", "layer_proc", "exec_time"], axis=1)

In [15]:
df_results

  dataset drop_modality   fpr95   auroc  id_acc
0     UCF         video  0.4333  0.8646  0.8689
1     HAC         video  0.3387  0.8981  0.8689
2    EPIC         video  0.1699  0.9598  0.8689
3     UCF          flow  0.4778  0.8598  0.8700
4     HAC          flow  0.4356  0.8849  0.8700
5    EPIC          flow  0.1756  0.9582  0.8700

normaliser les valeurs et les ordres

In [16]:
df_results.fpr95 = df_results.fpr95.apply(lambda x:x*100)
df_results.auroc = df_results.auroc.apply(lambda x:x*100)
df_results.id_acc = df_results.id_acc.apply(lambda x:x*100)

afficher les colonnes comme dans le tableau du papier

In [22]:
results = {"modality": [], "UCF_fpr95": [], "UCF_auroc":[], "EPIC_fpr95": [], "EPIC_auroc": [], "HAC_fpr95":[], "HAC_auroc":[]}
metrics = ["fpr95", "auroc"]
for name, group in df_results.groupby(by="drop_modality"):
    results["modality"].append(name)
    for i, dataset in group.iterrows():
        for metric in metrics:
            results[
                f"{dataset['dataset']}_{metric}"
                ].append(dataset[metric])
        

#ordre_method = ['msp', 'ebo', 'maxlogit', 'Mahalanobis', 'react', 'ash', 'gen', 'knn', 'vim']
ordre_modalites = ["video", "flow"]
results = pd.DataFrame(results)
results['modality'] = pd.Categorical(results['modality'], categories=ordre_modalites, ordered=True)
results = results.sort_values(['modality'])
results.to_csv("react_modality_wise_far_ood_baseline.csv", index=False)
results

  modality  UCF_fpr95  UCF_auroc  EPIC_fpr95  EPIC_auroc  HAC_fpr95  HAC_auroc
1    video      43.33      86.46       16.99       95.98      33.87      89.81
0     flow      47.78      85.98       17.56       95.82      43.56      88.49

In [23]:
results.to_csv("react_modality_wise_far_ood_baseline.csv", index=False)

# Max de MSP modality_wise

In [27]:
modalities = ["video", "flow"]
ood_datasets = ["UCF", "HAC", "EPIC"]
#sparsification_methods = {"react_": "--use_react"}

In [32]:
template = "id_HMDB_ood_{}_conf_baseline_best_react_{}_eval.npy"

In [ ]:
confidence_scores = {}
for dataset in ood_datasets:
    for modality in modalities:
        path = ("/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/"+
                template.format(dataset, modality))
        confidence_scores[dataset+"_"+modality] = np.load()

True
True
True
True
True
True

In [35]:
conf = np.load("/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/"+
                template.format("UCF", "video"))

In [37]:
conf

array([0.3306899 , 0.56608516, 0.767834  , ..., 0.6596376 , 0.41265956,
       0.49398056], dtype=float32)

In [39]:
t1 = np.array([1,2,3])
t2 = np.array([0,3,4])
t3 = np.array([-1, -1,-1])
t = [t1,t2,t3]
t

[array([1, 2, 3]), array([0, 3, 4]), array([-1, -1, -1])]

In [40]:
np.vstack(t)

array([[ 1,  2,  3],
       [ 0,  3,  4],
       [-1, -1, -1]])

In [42]:
np.max(t, axis=0)

array([1, 3, 4])

## resultats

In [55]:
df_resultats_max = pd.read_csv("/data/maouche/MultiOOD/results_moda_wise_ucf_react_video_FINAL.csv")

In [56]:
df_resultats_max.drop(["backbone", "exec_time"], axis=1)

  aggregation_method dataset layer_proc   fpr95   auroc  id_acc
0                max     UCF      react  0.5770  0.8314  0.8666
1                max    EPIC      react  0.1995  0.9506  0.8666
2                max     HAC      react  0.5268  0.8618  0.8666
3               mean     UCF      react  0.4949  0.8525  0.8666
4               mean    EPIC      react  0.1836  0.9567  0.8666
5               mean     HAC      react  0.4036  0.8866  0.8666