In [1]:
import pandas as pd
import os
import numpy as np
module_path = "/data/maouche/MultiOOD"
import sys
if module_path not in sys.path:
    sys.path.append(module_path)
from utils_mounir import normalize_columns, drop_columns

In [2]:
ordre_dataset = ['UCF', 'EPIC', 'HAC']
ordre_modalites = ["video", "flow"]

# Far OOD Video Flow

In [4]:
df_results = pd.read_csv( "results_moda_wise_ucf_react_video_flow.csv")
df_results = normalize_columns(drop_columns(df_results, ["backbone", "method", "layer_proc", "exec_time"])
                               , ["fpr95", "auroc","id_acc"])
df_results

  dataset drop_modality  fpr95  auroc  id_acc
0     UCF         video  43.33  86.46   86.89
1    EPIC         video  16.99  95.98   86.89
2     HAC         video  33.87  89.81   86.89
3     UCF          flow  47.78  85.98   87.00
4    EPIC          flow  17.56  95.82   87.00
5     HAC          flow  43.56  88.49   87.00

afficher les colonnes comme dans le tableau du papier

In [22]:
results = {"modality": [], "UCF_fpr95": [], "UCF_auroc":[], "EPIC_fpr95": [], "EPIC_auroc": [], "HAC_fpr95":[], "HAC_auroc":[]}
metrics = ["fpr95", "auroc"]
for name, group in df_results.groupby(by="drop_modality"):
    results["modality"].append(name)
    for i, dataset in group.iterrows():
        for metric in metrics:
            results[
                f"{dataset['dataset']}_{metric}"
                ].append(dataset[metric])
        

#ordre_method = ['msp', 'ebo', 'maxlogit', 'Mahalanobis', 'react', 'ash', 'gen', 'knn', 'vim']
ordre_modalites = ["video", "flow"]
results = pd.DataFrame(results)
results['modality'] = pd.Categorical(results['modality'], categories=ordre_modalites, ordered=True)
results = results.sort_values(['modality'])
results.to_csv("react_modality_wise_far_ood_baseline.csv", index=False)
results

  modality  UCF_fpr95  UCF_auroc  EPIC_fpr95  EPIC_auroc  HAC_fpr95  HAC_auroc
1    video      43.33      86.46       16.99       95.98      33.87      89.81
0     flow      47.78      85.98       17.56       95.82      43.56      88.49

## Max de MSP modality_wise

In [ ]:
modalities = ["video", "flow"]
ood_datasets = ["UCF", "HAC", "EPIC"]

In [ ]:
template = "id_HMDB_ood_{}_conf_baseline_best_react_{}_eval.npy"
confidence_scores = {}
for dataset in ood_datasets:
    for modality in modalities:
        path = ("/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/"+
                template.format(dataset, modality))
        confidence_scores[dataset+"_"+modality] = np.load(path)

True
True
True
True
True
True

In [ ]:
conf = np.load("/data/maouche/MultiOOD/HMDB-rgb-flow/saved_files/"+
                template.format("UCF", "video"))
conf

array([0.3306899 , 0.56608516, 0.767834  , ..., 0.6596376 , 0.41265956,
       0.49398056], dtype=float32)

## resultats

In [55]:
df_resultats_max = pd.read_csv("/data/maouche/MultiOOD/results_moda_wise_ucf_react_video_FINAL.csv")

In [56]:
df_resultats_max.drop(["backbone", "exec_time"], axis=1)

  aggregation_method dataset layer_proc   fpr95   auroc  id_acc
0                max     UCF      react  0.5770  0.8314  0.8666
1                max    EPIC      react  0.1995  0.9506  0.8666
2                max     HAC      react  0.5268  0.8618  0.8666
3               mean     UCF      react  0.4949  0.8525  0.8666
4               mean    EPIC      react  0.1836  0.9567  0.8666
5               mean     HAC      react  0.4036  0.8866  0.8666

# Near OOD Video Flow Audio

In [18]:
df_results = pd.read_csv("../../results_postprocessings_moda_wise_near_ood_react.csv")
df_results = normalize_columns(drop_columns(df_results, ["backbone", "method", "layer_proc", "exec_time"])
                               , ["fpr95", "auroc","id_acc"])

#df_results.to_csv("react_modality_wise_vfa_near_ood_baseline.csv", index=False)

df_results

  dataset drop_modality  fpr95  auroc  id_acc
0    HMDB         video  43.57  87.85   89.54
1     UCF         video  24.08  95.40   99.22
2    EPIC         video  79.66  66.97   71.64
3    HMDB          flow  44.88  87.44   89.98
4     UCF          flow  21.84  95.87   99.32
5    EPIC          flow  79.29  66.56   70.71

In [20]:
df_results = pd.read_csv("../../aggregation_moda_wise_vfaaa_near_ood.csv")
df_results = normalize_columns(drop_columns(df_results, ["backbone", "layer_proc", "exec_time"])
                               , ["fpr95", "auroc","id_acc"])

df_results

  aggregation_method dataset  fpr95  auroc  id_acc
0                max    EPIC  83.96  62.59   73.13
1               mean    EPIC  79.48  64.36   73.13

# Near OOD Video Flow

In [14]:
df_results = pd.read_csv("../../aggregation_moda_wise_near_ood.csv")
df_results = normalize_columns(drop_columns(df_results, ["backbone", "layer_proc", "exec_time"])
                               , ["fpr95", "auroc","id_acc"])
df_results

  aggregation_method dataset  fpr95  auroc  id_acc
0                max    HMDB  63.18  84.72   89.76
1                max     UCF  38.54  93.56   99.22
2                max    EPIC  89.55  63.42   71.27
3               mean    HMDB  47.93  86.77   89.76
4               mean     UCF  29.71  94.80   99.22
5               mean    EPIC  86.38  64.89   71.27