In [ ]:
import pandas as pd

/home/maouche/.conda/envs/multiood/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
ordre_method = ['msp', 'ebo', 'maxlogit', 'Mahalanobis', 'react', 'ash', 'gen', 'knn', 'vim']
ordre_dataset = ['UCF', 'EPIC', 'HAC']
ordre_layer_proc = ['none', 'ash', 'react']

In [3]:
results_file = "results_postprocessings_near_ood.csv"
df_results = pd.read_csv(results_file)

In [ ]:
df_results_baseline = df_results[df_results.backbone == 'baseline'].drop("backbone", axis=1) 
df_results_a2dnpm = df_results[df_results.backbone == 'a2d_npmix'].drop("backbone", axis=1)

normaliser les valeurs et les ordres

In [ ]:
df_results_baseline['method'] = pd.Categorical(df_results_baseline['method'], categories=ordre_method, ordered=True)
df_results_baseline['layer_proc'] = pd.Categorical(df_results_baseline['layer_proc'], categories=ordre_layer_proc, ordered=True)

# Trier d'abord par 'method', puis par 'dataset'
df_results_baseline = df_results_baseline.sort_values(['method', 'layer_proc']) #['method', 'dataset', 'layer_proc']
df_results_baseline.fpr95 = df_results_baseline.fpr95.apply(lambda x:x*100)
df_results_baseline.auroc = df_results_baseline.auroc.apply(lambda x:x*100)
df_results_baseline.id_acc = df_results_baseline.id_acc.apply(lambda x:x*100)

In [ ]:
df_results_a2dnpm['method'] = pd.Categorical(df_results_a2dnpm['method'], categories=ordre_method, ordered=True)
df_results_a2dnpm['layer_proc'] = pd.Categorical(df_results_a2dnpm['layer_proc'], categories=ordre_layer_proc, ordered=True)

# Trier d'abord par 'method', puis par 'dataset'
df_results_a2dnpm = df_results_a2dnpm.sort_values(['method', 'layer_proc']) #['method', 'dataset', 'layer_proc']
df_results_a2dnpm.fpr95 = df_results_a2dnpm.fpr95.apply(lambda x:x*100)
df_results_a2dnpm.auroc = df_results_a2dnpm.auroc.apply(lambda x:x*100)
df_results_a2dnpm.id_acc = df_results_a2dnpm.id_acc.apply(lambda x:x*100)

afficher les colonnes comme dans le tableau du papier

In [ ]:
table1_baseline = {"method": [], "HMDB_fpr95":[], "HMDB_auroc": [],
           "UCF_fpr95": [], "UCF_auroc": [], "EPIC_fpr95": [], "EPIC_auroc": []}#, "HAC_fpr95":[], "HAC_auroc":[]}
metrics = ["fpr95", "auroc"]
for name, group in df_results_baseline.groupby(by="method"):
    
    table1_baseline["method"].append(name)
    for i, dataset in group.iterrows():
        for metric in metrics:
            table1_baseline[
                f"{dataset['dataset']}_{metric}"
                ].append(dataset[metric])
        

ordre_method = ['msp', 'ebo', 'maxlogit', 'Mahalanobis', 'react', 'ash', 'gen', 'knn', 'vim']
table1_baseline = pd.DataFrame(table1_baseline)
table1_baseline['method'] = pd.Categorical(table1_baseline['method'], categories=ordre_method, ordered=True)
table1_baseline = table1_baseline.sort_values(['method'])
table1_baseline.to_csv("tableau1_near_ood_baseline.csv")
table1_baseline

,method,HMDB_fpr95,HMDB_auroc,UCF_fpr95,UCF_auroc,EPIC_fpr95,EPIC_auroc
0,msp,44.9,87.6,22.0,95.7,76.3,67.6
1,ebo,42.9,87.4,22.4,96.1,76.7,68.3
2,maxlogit,42.9,87.7,22.4,96.0,76.9,68.3
3,Mahalanobis,42.9,85.6,12.1,97.1,98.7,43.0
4,react,41.6,87.8,25.4,95.9,84.0,65.9
5,ash,52.9,87.1,31.9,94.0,76.9,67.9
6,gen,45.3,87.2,24.8,95.4,76.9,68.5
7,knn,42.7,88.4,15.6,96.9,78.2,63.1
8,vim,39.7,87.4,12.5,97.7,77.1,65.6

In [26]:
table1_a2dnpmix = {"method": [], "HMDB_fpr95":[], "HMDB_auroc": [],
           "UCF_fpr95": [], "UCF_auroc": [], "EPIC_fpr95": [], "EPIC_auroc": []}#, "HAC_fpr95":[], "HAC_auroc":[]}
metrics = ["fpr95", "auroc"]
for name, group in df_results_a2dnpm.groupby(by="method"):
    
    table1_a2dnpmix["method"].append(name)
    for i, dataset in group.iterrows():
        for metric in metrics:
            table1_a2dnpmix[
                f"{dataset['dataset']}_{metric}"
                ].append(dataset[metric])
        

ordre_method = ['msp', 'ebo', 'maxlogit', 'Mahalanobis', 'react', 'ash', 'gen', 'knn', 'vim']
table1_a2dnpmix = pd.DataFrame(table1_a2dnpmix)
table1_a2dnpmix['method'] = pd.Categorical(table1_a2dnpmix['method'], categories=ordre_method, ordered=True)
table1_a2dnpmix = table1_a2dnpmix.sort_values(['method'])
table1_a2dnpmix.to_csv("tableau1_near_ood_a2dnpmix.csv", index=False)
table1_a2dnpmix

,method,HMDB_fpr95,HMDB_auroc,UCF_fpr95,UCF_auroc,EPIC_fpr95,EPIC_auroc
0,msp,33.8,88.8,8.0,98.2,67.2,71.5
1,ebo,35.9,88.9,6.5,98.5,67.9,73.8
2,maxlogit,35.9,89.0,6.5,98.5,67.0,73.5
3,Mahalanobis,41.0,87.8,8.0,98.0,94.8,44.4
4,react,38.3,88.7,12.4,97.3,66.6,73.1
5,ash,35.9,89.2,10.7,97.8,66.2,73.1
6,gen,36.4,89.8,7.7,98.3,65.3,75.2
7,knn,33.6,90.0,12.0,97.7,70.9,70.5
8,vim,36.2,88.8,4.6,98.7,67.7,69.1