In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Tableau 7 far ood hmdb ++

In [ ]:
far_ood_hmdb = pd.read_csv("reimpl_papier.csv")
far_ood_hmdb

         method dataset layer_proc   fpr95   auroc  id_acc       exec_time
0           msp     UCF       none  40.593  88.000  86.773             NaN
1           msp     HAC       none  28.620  91.568  86.773             NaN
2           msp    EPIC       none  13.455  96.422  86.773             NaN
3           ebo     UCF       none  37.058  89.712  86.773             NaN
4           ebo     HAC       none  23.033  94.447  86.773             NaN
5           ebo    EPIC       none   7.184  97.598  86.773             NaN
6      maxlogit     UCF       none  37.058  89.729  86.773             NaN
7      maxlogit     HAC       none  23.147  94.250  86.773             NaN
8      maxlogit    EPIC       none   7.070  97.726  86.773             NaN
9   Mahalanobis     UCF       none  27.708  91.211  86.773             NaN
10  Mahalanobis     HAC       none   7.754  98.218  86.773             NaN
11  Mahalanobis    EPIC       none  12.429  96.100  86.773             NaN
12        react     UCF      react  37.286  89.685  86.545  0:00:00.391833
13        react     HAC      react  20.867  95.056  86.545  0:00:00.553978
14        react    EPIC      react   7.184  97.458  86.545  0:00:01.281754
15          ash     UCF        ash  38.769  89.552  86.203  0:00:00.530498
16          ash     HAC        ash  23.489  94.482  86.203  0:00:00.626123
17          ash    EPIC        ash   6.956  98.251  86.203  0:00:00.932298
18          gen     UCF       none  37.400  91.235  86.773             NaN
19          gen     HAC       none  24.287  94.326  86.773             NaN
20          gen    EPIC       none   5.131  99.024  86.773             NaN
21          knn     UCF       none  33.181  91.948  86.773             NaN
22          knn     HAC       none  13.569  97.248  86.773             NaN
23          knn    EPIC       none   5.587  98.990  86.773             NaN
24          vim     UCF       none  26.910  92.274  86.773  0:00:55.357998
25          vim     HAC       none   6.385  98.563  86.773  0:00:47.698387
26          vim    EPIC       none   5.587  98.062  86.773  0:00:49.830122

In [ ]:
results = {"method": [], "UCF_fpr95": [], "UCF_auroc":[], "EPIC_fpr95": [], "EPIC_auroc": [], "HAC_fpr95":[], "HAC_auroc":[]}
metrics = ["fpr95", "auroc"]
for name, group in far_ood_hmdb.groupby(by="method"):
    
    results["method"].append(name)
    for i, dataset in group.iterrows():
        for metric in metrics:
            results[
                f"{dataset['dataset']}_{metric}"
                ].append(dataset[metric])
        

ordre_method = ['msp', 'ebo', 'maxlogit', 'Mahalanobis', 'react', 'ash', 'gen', 'knn', 'vim']
results = pd.DataFrame(results)
results['method'] = pd.Categorical(results['method'], categories=ordre_method, ordered=True)
results = results.sort_values(['method'])
#results.to_csv("tableau7_far_ood_hmdb_++.csv", index=False)
results

,method,UCF_fpr95,UCF_auroc,EPIC_fpr95,EPIC_auroc,HAC_fpr95,HAC_auroc
6,msp,40.593,88.000,13.455,96.422,28.620,91.568
2,ebo,37.058,89.712,7.184,97.598,23.033,94.447
5,maxlogit,37.058,89.729,7.070,97.726,23.147,94.250
0,Mahalanobis,27.708,91.211,12.429,96.100,7.754,98.218
7,react,37.286,89.685,7.184,97.458,20.867,95.056
1,ash,38.769,89.552,6.956,98.251,23.489,94.482
3,gen,37.400,91.235,5.131,99.024,24.287,94.326
4,knn,33.181,91.948,5.587,98.990,13.569,97.248
8,vim,26.910,92.274,5.587,98.062,6.385,98.563