In [1]:
import pandas as pd

In [2]:
ordre_method = ['msp', 'ebo', 'maxlogit', 'Mahalanobis', 'react', 'ash', 'gen', 'knn', 'vim']
ordre_dataset = ['UCF', 'EPIC', 'HAC']
ordre_layer_proc = ['none', 'ash', 'react']

In [13]:
results_file = "results_postprocessings_far_ood_baseline.csv"
df_results_baseline = pd.read_csv(results_file).drop(["backbone", "layer_proc"], axis=1)

normaliser les valeurs et les ordres

In [14]:
df_results_baseline.fpr95 = df_results_baseline.fpr95.apply(lambda x:x*100)
df_results_baseline.auroc = df_results_baseline.auroc.apply(lambda x:x*100)
df_results_baseline.id_acc = df_results_baseline.id_acc.apply(lambda x:x*100)

afficher les colonnes comme dans le tableau du papier

In [16]:
results = {"method": [], "UCF_fpr95": [], "UCF_auroc":[], "EPIC_fpr95": [], "EPIC_auroc": [], "HAC_fpr95":[], "HAC_auroc":[]}
metrics = ["fpr95", "auroc"]
for name, group in df_results_baseline.groupby(by="method"):
    
    results["method"].append(name)
    for i, dataset in group.iterrows():
        for metric in metrics:
            results[
                f"{dataset['dataset']}_{metric}"
                ].append(dataset[metric])
        

ordre_method = ['msp', 'ebo', 'maxlogit', 'Mahalanobis', 'react', 'ash', 'gen', 'knn', 'vim']
results = pd.DataFrame(results)
results['method'] = pd.Categorical(results['method'], categories=ordre_method, ordered=True)
results = results.sort_values(['method'])
results.to_csv("tableau7_far_ood_hmdb_baseline.csv", index=False)
results

,method,UCF_fpr95,UCF_auroc,EPIC_fpr95,EPIC_auroc,HAC_fpr95,HAC_auroc
6,msp,46.41,86.07,17.22,95.75,39.79,88.78
2,ebo,44.70,87.95,7.87,97.64,33.52,92.25
5,maxlogit,44.70,87.95,9.24,97.72,33.30,92.11
0,Mahalanobis,41.96,87.06,18.02,93.46,11.29,97.27
7,react,43.79,88.09,7.41,97.59,30.56,92.86
1,ash,53.93,84.16,20.18,95.93,43.44,90.20
3,gen,45.61,87.88,8.44,98.28,38.65,91.25
4,knn,37.63,89.26,9.92,97.92,21.21,96.03
8,vim,33.30,91.48,5.59,97.98,12.88,97.10

In [26]:
table1_a2dnpmix = {"method": [], "HMDB_fpr95":[], "HMDB_auroc": [],
           "UCF_fpr95": [], "UCF_auroc": [], "EPIC_fpr95": [], "EPIC_auroc": []}#, "HAC_fpr95":[], "HAC_auroc":[]}
metrics = ["fpr95", "auroc"]
for name, group in df_results_a2dnpm.groupby(by="method"):
    
    table1_a2dnpmix["method"].append(name)
    for i, dataset in group.iterrows():
        for metric in metrics:
            table1_a2dnpmix[
                f"{dataset['dataset']}_{metric}"
                ].append(dataset[metric])
        

ordre_method = ['msp', 'ebo', 'maxlogit', 'Mahalanobis', 'react', 'ash', 'gen', 'knn', 'vim']
table1_a2dnpmix = pd.DataFrame(table1_a2dnpmix)
table1_a2dnpmix['method'] = pd.Categorical(table1_a2dnpmix['method'], categories=ordre_method, ordered=True)
table1_a2dnpmix = table1_a2dnpmix.sort_values(['method'])
table1_a2dnpmix.to_csv("tableau1_near_ood_a2dnpmix.csv", index=False)
table1_a2dnpmix

,method,HMDB_fpr95,HMDB_auroc,UCF_fpr95,UCF_auroc,EPIC_fpr95,EPIC_auroc
0,msp,33.8,88.8,8.0,98.2,67.2,71.5
1,ebo,35.9,88.9,6.5,98.5,67.9,73.8
2,maxlogit,35.9,89.0,6.5,98.5,67.0,73.5
3,Mahalanobis,41.0,87.8,8.0,98.0,94.8,44.4
4,react,38.3,88.7,12.4,97.3,66.6,73.1
5,ash,35.9,89.2,10.7,97.8,66.2,73.1
6,gen,36.4,89.8,7.7,98.3,65.3,75.2
7,knn,33.6,90.0,12.0,97.7,70.9,70.5
8,vim,36.2,88.8,4.6,98.7,67.7,69.1