In [2]:
import pandas as pd
import os
import numpy as np
#module_path = "/data/maouche/MultiOOD"
import sys
# if module_path not in sys.path:
#     sys.path.append(module_path)
from utils_mounir import normalize_columns, drop_columns, column_names, order_modalities

results_path = "resultats/modality_wise/ash"

/home/maouche/.conda/envs/multiood/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Ash

## Far OOD

In [3]:
df_results = pd.read_csv("eval_moda_wise_ash_far_ood.csv")
df_results = normalize_columns(drop_columns(df_results, ["backbone", "method", "layer_proc", "exec_time"])
                               , ["fpr95", "auroc","id_acc"])
df_results

  dataset drop_modality     fpr95    auroc    id_acc
0     UCF         video  55.53022  81.9079  85.74686
1     UCF          flow  46.97834  84.8341  86.77309
2    EPIC         video  29.41847  90.4236  85.74686
3    EPIC          flow  20.63854  93.5735  86.77309

In [ ]:
df2 = column_names(normalize_columns(drop_columns(pd.read_csv("aggregation_far_ash.csv"), ["exec_time"]), ["fpr95", "auroc"]))
df2

             method  UCF_fpr95  UCF_auroc  EPIC_fpr95  EPIC_auroc
0               max      55.30      82.64       28.16       91.69
1  max_perturbation      55.53      81.91       29.42       90.42
2              mean      47.89      85.09       20.98       93.96
3               min      47.43      85.14       21.09       93.90

## Near OOD

In [2]:
df_results = pd.read_csv(os.path.join(results_path, "eval_moda_wise_ash_near_ood.csv"))
df_results = normalize_columns(drop_columns(df_results, ["backbone", "method", "layer_proc", "exec_time"])
                               , ["fpr95", "auroc","id_acc"])
df_results

  dataset drop_modality     fpr95    auroc    id_acc
0    HMDB         video  47.93028  86.3282  89.32462
1     UCF         video  26.11650  94.9020  99.41748
2    EPIC         video  76.67910  65.5557  69.96269
3    HMDB          flow  45.31590  85.6925  87.79956
4     UCF          flow  26.89320  94.2993  98.73786
5    EPIC          flow  72.76119  68.3474  69.02985

In [3]:
df_results = order_modalities(column_names(df_results))
df_results

,modality,HMDB_fpr95,HMDB_auroc,UCF_fpr95,UCF_auroc,EPIC_fpr95,EPIC_auroc
1,video,47.93028,86.3282,26.1165,94.9020,76.67910,65.5557
0,flow,45.31590,85.6925,26.8932,94.2993,72.76119,68.3474

In [ ]:
df_agg = normalize_columns(drop_columns(pd.read_csv("aggregation_ash_near_ood.csv"), ["exec_time"]), ["fpr95", "auroc"])
df_agg
#old

   backbone aggregation_method dataset layer_proc     fpr95    auroc    id_acc
0  baseline               mean    HMDB        ash  47.93028  84.4809  0.885621
1  baseline               mean     UCF        ash  30.09709  93.9821  0.990777
2  baseline               mean    EPIC        ash  75.55970  68.1447  0.694963
3  baseline                max    HMDB        ash  74.94553  74.3672  0.893246
4  baseline                max     UCF        ash  58.25243  86.5433  0.994175
5  baseline                max    EPIC        ash  86.38060  55.8922  0.699627

In [2]:
df_agg = column_names(normalize_columns(drop_columns(pd.read_csv("aggregation_near_ash.csv"), ["exec_time"]), ["fpr95", "auroc"]))
df_agg

,method,HMDB_fpr95,HMDB_auroc,UCF_fpr95,UCF_auroc,EPIC_fpr95,EPIC_auroc
0,max,48.15,86.41,26.12,94.73,76.31,67.28
1,max_perturbation,47.93,86.33,26.12,94.90,76.68,65.56
2,mean,44.88,86.93,24.56,95.05,74.81,67.66
3,min,44.88,86.56,25.73,94.97,74.44,67.62

## Comb

In [ ]:
df_agg = column_names(normalize_columns(drop_columns(pd.read_csv("aggregation_near_comb_ash.csv"), ["exec_time"]), ["fpr95", "auroc"]))
df_agg

             method  EPIC_fpr95  EPIC_auroc
0               max       78.36       67.39
1  max_perturbation       79.29       63.84
2              mean       74.07       67.35
3               min       73.51       67.41

# React

## Far

In [ ]:
df_results = pd.read_csv("eval_moda_wise_ash_far_ood.csv")
df_results = normalize_columns(drop_columns(df_results, ["backbone", "method", "layer_proc", "exec_time"])
                               , ["fpr95", "auroc","id_acc"])
df_results

In [19]:
df2 = column_names(normalize_columns(drop_columns(pd.read_csv("aggregation_far_react.csv"), ["exec_time"]), ["fpr95", "auroc"]))
df2

             method  UCF_fpr95  UCF_auroc  EPIC_fpr95  EPIC_auroc
0               max      45.95      86.16       16.99       95.91
1  max_perturbation      47.78      85.98       17.56       95.82
2              mean      44.24      86.38       17.33       95.98
3               min      44.13      86.43       17.45       95.95

## Near

In [3]:
df2 = column_names(normalize_columns(drop_columns(pd.read_csv("aggregation_near_react.csv"), ["exec_time"]), ["fpr95", "auroc"]))
df2

,method,HMDB_fpr95,HMDB_auroc,UCF_fpr95,UCF_auroc,EPIC_fpr95,EPIC_auroc
0,max,45.32,87.49,22.23,95.78,77.24,67.69
1,max_perturbation,43.57,87.85,21.84,95.87,79.66,66.97
2,mean,43.79,87.88,22.33,95.72,81.90,66.59
3,min,44.01,87.92,22.82,95.62,82.28,65.89

## Comb

In [2]:
df_results = pd.read_csv("eval_moda_wise_near_ood_vfa_comb_react.csv")
df_results = normalize_columns(drop_columns(df_results, ["backbone", "method", "layer_proc", "exec_time"])
                               , ["fpr95", "auroc","id_acc"])
df_results

  dataset drop_modality     fpr95    auroc    id_acc
0    EPIC    video_flow  75.55970  66.5857  72.94776
1    EPIC    flow_audio  74.44030  67.3195  73.32090
2    EPIC   video_audio  73.69403  67.1087  72.57463

In [ ]:
df_agg = normalize_columns(drop_columns(pd.read_csv("aggregation_moda_wise_vfa_comb_near_ood_react.csv"), ["exec_time"]), ["fpr95", "auroc"])
df_agg #old

   backbone aggregation_method dataset layer_proc     fpr95    auroc    id_acc
0  baseline               mean    EPIC      react  74.25373  66.7590  0.729478
1  baseline                max    EPIC      react  78.54478  64.4498  0.733209

In [16]:
df_agg = column_names(normalize_columns(drop_columns(pd.read_csv("aggregation_near_comb_react.csv"), ["exec_time"]), ["fpr95", "auroc"]))
df_agg

             method  EPIC_fpr95  EPIC_auroc
0               max       71.64       69.41
1  max_perturbation       75.56       66.59
2              mean       76.31       66.83
3               min       76.87       65.22